name: mac-build

on: [push, pull_request]

jobs:
  mac-build-gui:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: ouuan/install-qt-action@ouuan
      with:
        version: 5.14.2
        target: desktop
        host: mac
        install-deps: true

    - name: Prepare
      run: |
        ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11/ /usr/local/include/X11

    - name: make
      run: ./build.sh -DQt5_PATH="${Qt5_Dir}"

    - name: Package
      working-directory: bin/Seg3D
      run: |
        make package
        chmod +x repair_package.sh
        ./repair_package.sh

    - name: Upload installer
      uses: actions/upload-artifact@v1
      with:
        name: Seg3DMacInstaller
        path: bin/Seg3D/Seg3D2-2.4.4-Darwin.pkg
